import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  CheckSquare, 
  ThumbsUp, 
  ThumbsDown, 
  Edit3, 
  Mail, 
  User, 
  CheckCircle,
  AlertCircle,
  FileText
} from 'lucide-react';

export default function Approvals() {
  const [pendingEmails, setPendingEmails] = useState([]);
  const [selectedEmail, setSelectedEmail] = useState(null);
  const [loading, setLoading] = useState(true);
  const [notifyMsg, setNotifyMsg] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [editedBody, setEditedBody] = useState('');

  const fetchPending = async () => {
    try {
      setLoading(true);
      const response = await axios.get('/agents/emails');
      const pending = response.data.filter(e => e.status === 'pending');
      setPendingEmails(pending);
      if (pending.length > 0) {
        setSelectedEmail(pending[0]);
        setEditedBody(pending[0].body);
      } else {
        setSelectedEmail(null);
      }
    } catch (err) {
      console.error('Failed to fetch approvals queue:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPending();
  }, []);

  const handleSelectEmail = (email) => {
    setSelectedEmail(email);
    setEditedBody(email.body);
    setIsEditing(false);
  };

  const handleApprove = async () => {
    if (!selectedEmail) return;
    try {
      setNotifyMsg('');
      
      // If body was edited, save first (simulated patch or route write)
      if (isEditing) {
        selectedEmail.body = editedBody;
      }

      await axios.post(`/agents/emails/${selectedEmail._id}/approve`);
      setNotifyMsg(`Outreach email approved for ${selectedEmail.customer?.name}.`);
      
      // Remove from pending list
      const remaining = pendingEmails.filter(e => e._id !== selectedEmail._id);
      setPendingEmails(remaining);
      setSelectedEmail(remaining.length > 0 ? remaining[0] : null);
      if (remaining.length > 0) {
        setEditedBody(remaining[0].body);
      }
      setIsEditing(false);
      setTimeout(() => setNotifyMsg(''), 4000);
    } catch (err) {
      setNotifyMsg('Approve operation failed.');
    }
  };

  const handleReject = async () => {
    if (!selectedEmail) return;
    try {
      setNotifyMsg('');
      await axios.post(`/agents/emails/${selectedEmail._id}/reject`);
      setNotifyMsg(`Email draft for ${selectedEmail.customer?.name} rejected.`);
      
      const remaining = pendingEmails.filter(e => e._id !== selectedEmail._id);
      setPendingEmails(remaining);
      setSelectedEmail(remaining.length > 0 ? remaining[0] : null);
      if (remaining.length > 0) {
        setEditedBody(remaining[0].body);
      }
      setIsEditing(false);
      setTimeout(() => setNotifyMsg(''), 4000);
    } catch (err) {
      setNotifyMsg('Reject operation failed.');
    }
  };

  return (
    <div className="space-y-6 h-[calc(100vh-10rem)] flex flex-col">
      {/* Header Panel */}
      <motion.div 
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="p-6 rounded-3xl bg-gradient-to-r from-accentPurple/10 via-accentIndigo/10 to-transparent border border-accentPurple/15 flex items-center justify-between shrink-0"
      >
        <div>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center space-x-2">
            <CheckSquare className="text-accentPurple" size={20} />
            <span>Human-in-the-Loop Approvals Queue</span>
          </h2>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Review and adjust outbound sales copies generated by the AI Email agent before sending.
          </p>
        </div>
      </motion.div>

      {notifyMsg && (
        <div className="flex items-center space-x-2.5 p-3.5 rounded-xl border border-accentPurple/25 bg-accentPurple/5 text-accentPurple text-sm shrink-0">
          <CheckCircle size={18} />
          <span>{notifyMsg}</span>
        </div>
      )}

      {loading ? (
        <div className="flex-1 flex items-center justify-center">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-accentPurple border-t-transparent"></div>
        </div>
      ) : pendingEmails.length === 0 ? (
        /* Empty approvals state */
        <div className="flex flex-col items-center justify-center border border-dashed border-slate-200 dark:border-slate-800 rounded-3xl bg-slate-50/50 dark:bg-slate-950/10 flex-1 py-16">
          <CheckSquare size={32} className="text-slate-405 mb-2" />
          <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Approvals Queue Clear</h3>
          <p className="text-xs text-slate-400 mt-1">No outreach campaigns require review at this time.</p>
        </div>
      ) : (
        /* Split view */
        <div className="flex flex-1 border border-slate-200 dark:border-slate-800/80 rounded-2xl overflow-hidden bg-white dark:bg-[#0c0d14] min-h-0 shadow-sm">
          {/* Left Panel: Pending drafts queue list */}
          <div className="w-1/3 border-r border-slate-200 dark:border-slate-800 flex flex-col min-w-[280px]">
            <div className="p-4 border-b border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/20 text-xs font-bold text-slate-500 uppercase tracking-widest">
              Pending approvals ({pendingEmails.length})
            </div>
            
            <div className="flex-1 overflow-y-auto divide-y divide-slate-100 dark:divide-slate-900/60">
              {pendingEmails.map((email) => (
                <button
                  key={email._id}
                  onClick={() => handleSelectEmail(email)}
                  className={`
                    w-full text-left p-4 hover:bg-slate-50/50 dark:hover:bg-[#121420]/30 transition-colors flex flex-col space-y-1.5
                    ${selectedEmail?._id === email._id ? 'bg-accentPurple/5 border-l-4 border-accentPurple' : 'border-l-4 border-transparent'}
                  `}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-800 dark:text-slate-200 text-xs truncate max-w-[150px]">
                      {email.customer?.name}
                    </span>
                    <span className="px-1.5 py-0.5 rounded bg-red-500/10 text-red-500 font-extrabold text-[8px]">
                      Score: {email.customer?.score}
                    </span>
                  </div>
                  <p className="text-[10px] text-slate-500 dark:text-slate-500 truncate font-mono-custom">{email.customer?.email}</p>
                  <p className="text-xs text-slate-650 dark:text-slate-400 font-semibold truncate leading-tight mt-1">{email.subject}</p>
                </button>
              ))}
            </div>
          </div>

          {/* Right Panel: Approval details composer */}
          <div className="flex-1 flex flex-col min-w-0 bg-slate-50/30 dark:bg-slate-950/5">
            {selectedEmail ? (
              <div className="flex flex-col flex-1 min-h-0">
                {/* Meta details */}
                <div className="p-5 border-b border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0c0d14] space-y-3 shrink-0">
                  <div className="flex items-center space-x-2">
                    <div className="p-1 rounded-lg bg-slate-100 dark:bg-[#121420] text-slate-400">
                      <User size={15} />
                    </div>
                    <span className="text-xs font-semibold text-slate-500">Target Lead:</span>
                    <span className="text-xs font-bold text-slate-805 dark:text-slate-205 font-mono-custom">{selectedEmail.customer?.email}</span>
                  </div>

                  <h3 className="text-sm font-bold text-slate-900 dark:text-white leading-normal">
                    Subject: {selectedEmail.subject}
                  </h3>

                  {/* Recommendations */}
                  <div className="grid grid-cols-2 gap-4 text-[10px] p-3 rounded-xl bg-slate-50 dark:bg-[#121420]/30 border border-slate-100 dark:border-slate-900">
                    <div>
                      <span className="text-slate-450 block uppercase tracking-wider font-bold mb-1">Recommended Action</span>
                      <strong className="text-slate-800 dark:text-white">{selectedEmail.customer?.insights?.strategy || 'Discovery Demos'}</strong>
                    </div>
                    <div>
                      <span className="text-slate-450 block uppercase tracking-wider font-bold mb-1">Call To Action (CTA)</span>
                      <strong className="text-slate-800 dark:text-white">{selectedEmail.cta || 'Verify Discovery Call'}</strong>
                    </div>
                  </div>
                </div>

                {/* Body Workspace */}
                <div className="flex-1 p-5 bg-white dark:bg-[#090a0f] overflow-y-auto">
                  {isEditing ? (
                    <textarea
                      value={editedBody}
                      onChange={(e) => setEditedBody(e.target.value)}
                      className="w-full h-full bg-transparent border-none text-xs leading-relaxed text-slate-700 dark:text-slate-350 focus:outline-none resize-none font-mono-custom"
                    />
                  ) : (
                    <div className="whitespace-pre-line text-xs text-slate-750 dark:text-slate-350 leading-relaxed font-sans">
                      {editedBody}
                    </div>
                  )}
                </div>

                {/* Footer Controls */}
                <div className="p-4 border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0c0d14] flex items-center justify-between shrink-0">
                  <button
                    onClick={() => setIsEditing(!isEditing)}
                    className="flex items-center space-x-1.5 px-3.5 py-2 border border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-300 rounded-xl text-xs font-semibold hover:bg-slate-50 dark:hover:bg-slate-900"
                  >
                    <Edit3 size={13} />
                    <span>{isEditing ? 'Read Mode' : 'Edit Body'}</span>
                  </button>

                  <div className="flex items-center space-x-2">
                    <button
                      onClick={handleReject}
                      className="flex items-center space-x-1 px-3.5 py-2 border border-red-500/25 bg-red-500/5 text-red-500 hover:bg-red-500/10 rounded-xl text-xs font-semibold"
                    >
                      <ThumbsDown size={13} />
                      <span>Reject Draft</span>
                    </button>

                    <button
                      onClick={handleApprove}
                      className="flex items-center space-x-1.5 px-5 py-2.5 bg-gradient-to-r from-accentPurple to-accentIndigo text-white rounded-xl text-xs font-bold shadow-md hover:scale-[1.01] active:scale-[0.99] transition-transform"
                    >
                      <ThumbsUp size={13} />
                      <span>Approve Outreach</span>
                    </button>
                  </div>
                </div>

              </div>
            ) : (
              <div className="flex flex-1 items-center justify-center text-slate-400">
                Select a pending outreach from the left list.
              </div>
            )}
          </div>

        </div>
      )}
    </div>
  );
}
